### ISSUE TITLE
`npm install fetch-remote` installs wrong lib

### ISSUE THREAD

**Issue by julkue** [yeoman/fetch-remote#1]
It will install https://www.npmjs.com/package/fetch-remote
Yeoman fetch-remote is also not listed here: https://www.npmjs.com/search?q=fetch-remote

**Comment by SBoudrias** [comment]
It's not published yet. Haven't had time to fix the last wrinkles.

**Comment by julkue** [comment]
No problem. However, in the meantime you should add a note. I'll do that for you.
